services:
  myaktion:
    build: ./src/myaktion
    ports:
      - "8002:8002"
    environment:
      - DB_CONNECT=mariadb:3306
      - LOG_LEVEL=info
  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myaktion